# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00109eacbb028adf8a96bc32eac428227db187da9d10624b95a35b35be2bcab234e71fc0b657695f83b856adfaad5202c20477877ee4d324732deaf2f24352a8

test:
  secret_key_base: 5077281024b82ad3c345e06944021635c8389374adc69a338df60d9e64dc8c329685148c36b7cc31a54f209b4f3ebb60883829bdc6fa0bc91e9f503e5bae60ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
